# Generated by Django 2.2.28 on 2023-05-21 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('author_department', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paper_title', models.CharField(max_length=200)),
                ('paper_title_en', models.CharField(max_length=200)),
                ('paper_intro', models.CharField(max_length=500)),
                ('paper_summary', models.CharField(max_length=500)),
                ('paper_authors', models.ManyToManyField(to='detections.Author')),
            ],
            options={
                'db_table': 'papers',
            },
        ),
    ]
